revised DSL1 archive with untracked changes from Elion

diff --git a/archive/nextflow/runbin/run_ctp b/archive/nextflow/runbin/run_ctp
--- a/archive/nextflow/runbin/run_ctp
+++ b/archive/nextflow/runbin/run_ctp
@@ -37,7 +37,6 @@ preserve_work=no         # if --preserve_work  don't delete nextflow's ./work di
 resultloc="default"      # specify to put result folder somewhere other than ./analysis
 indir="default"          # specify to set a special dir to get fastq files from
 min_pct_hq_reads=50      # minimum % high quality reads
-email="stephen.grubb@jax.org"
 
 shift 2
 for iarg in "$@"
@@ -54,10 +53,6 @@ do
     --all_but_launch)
       all_but_launch=yes
       real=no
-      shift
-      ;;
-    --email=*)
-      email="${iarg#*=}"
       shift
       ;;
     --min_pct_hq_reads=*)
@@ -84,6 +79,7 @@ do
 done
 
 
+# general sanity checks...
 if [ $real == "yes" ]; then 
   GROUP=`id -gn`
   if [ "$USER" != "svc-pdx" -o $GROUP != "pdx-data" ]; then
@@ -92,8 +88,13 @@ if [ $real == "yes" ]; then
   fi
 fi
 
+if [ "$resultloc" == "" -o "$indir" == "" ]; then
+  echo "ERROR: $CMD quitting: zero-length arg detected, --resultloc or --indir "
+  exit 1
+fi
 
-# determine where the fastq files are and do sanity checks...
+
+# determine where the fastq files are and be sure there are two of them...
 if [ $indir == "default" ]; then
   indir=$PDX/seqdata/$MODEL/$SAMPLE/CTP
 fi
@@ -128,7 +129,7 @@ if [ $real != "yes" -a $resultloc == "default" ]; then
   outdir="test_run_$outdir"
 fi
 if [ -d $outdir ]; then
-  echo -n "ERROR: $CMD quitting: result folder already exists ($outdir). "
+  echo -n "Notice: $CMD quitting: result folder already exists ($outdir). "
   show_folder_status $outdir
   exit 1
 fi
@@ -172,8 +173,7 @@ fi
 jobname="pdx_${PLATFORM}_${MODEL}_${SAMPLE}"
 
 # launch the pipeline........   
-sbatch  --job-name=$jobname  \
-  --mail-user=$email  --mail-type=END \
+sbatch  --job-name=$jobname  --mail-type=NONE \
   -q batch   -t 72:00:00  --mem=2000  \
   nextflow -c ./params.config   run $PDX/$NF_SCRIPT   -profile slurm,singularity   -with-dag nf_reports/flowchart.pdf
 
